# syntax=docker/dockerfile:1
FROM debian:bookworm-slim

WORKDIR /app
EXPOSE 8080 8081
ENV ASPNETCORE_URLS="http://+:8080;http://+:8081" \
    ASPNETCORE_ENVIRONMENT="Development" \
    DOTNET_SYSTEM_GLOBALIZATION_INVARIANT="1"

COPY publish/GameWebsite.MockApi/ ./
RUN chmod +x ./GameWebsite.MockApi

ENTRYPOINT ["./GameWebsite.MockApi"]
